name: Deploy to Google Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: occhio-cloud
  REGION: us-central1
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and Deploy
      run: |
        gcloud builds submit \
          --config=cloudbuild.yaml \
          --substitutions=_OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},_DB_HOST=${{ secrets.DB_HOST }},_DB_USER=${{ secrets.DB_USER }},_DB_PASSWORD=${{ secrets.DB_PASSWORD }},_DB_NAME=${{ secrets.DB_NAME }}